# Generated by Django 5.0.7 on 2024-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='flightlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9999, unique=True)),
                ('slug', models.SlugField(max_length=9999, unique=True)),
                ('img', models.CharField(max_length=9999)),
            ],
        ),
    ]
