# Generated by Django 5.0.7 on 2024-10-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='travel_date',
            field=models.DateField(null=True),
        ),
    ]
