# Generated by Django 5.0.7 on 2024-10-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_cars_slug_alter_cars_img_alter_cars_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='slug',
        ),
    ]
