# Generated by Django 5.0.7 on 2024-10-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_cars_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(max_length=99, null=True),
        ),
    ]
