# Generated by Django 5.0.7 on 2024-10-04 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=99, null=True)),
                ('slug', models.SlugField(max_length=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=99, null=True)),
                ('slug', models.SlugField(max_length=99, null=True)),
                ('room_number', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkin_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.CharField(blank=True, max_length=9999, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotels')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
