# Generated by Django 5.0.7 on 2024-10-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotels_list_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='room_number',
        ),
    ]
