# Generated by Django 5.0.7 on 2024-10-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_checkin_date_list_check_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='check_date',
            field=models.DateField(null=True),
        ),
    ]
