# Generated by Django 5.0.7 on 2024-10-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_roomlist_category_delete_rooms_list_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='first',
        ),
        migrations.RemoveField(
            model_name='list',
            name='second',
        ),
        migrations.RemoveField(
            model_name='list',
            name='third',
        ),
    ]
