# Generated by Django 5.0.7 on 2024-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_list_deluxe_list_executive_list_fifth_list_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='four',
            new_name='firstdesc',
        ),
        migrations.RemoveField(
            model_name='list',
            name='honeymoon',
        ),
        migrations.RemoveField(
            model_name='list',
            name='price',
        ),
        migrations.AddField(
            model_name='list',
            name='firstprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='seconddesc',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='secondprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='thirddesc',
            field=models.TextField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='thirdprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
